---
title: "County Inflow-Outflow Consolidation"
author: "Bradley Parmer-Lohan"
date: "2024-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(stringr)
library(ggplot2)
```


```{r}
# reading these seperately because the format is different from 11-21
file_paths_csv = c(
"../data_raw/countyoutflow0809.csv",
"../data_raw/countyoutflow0910.csv",
"../data_raw/countyoutflow1011.csv")

dataframes_outflow <- lapply(file_paths_csv, read.csv)
master_outflow_csv <- do.call(rbind, lapply(dataframes_outflow, function(df) {
  select(df, State_Code_Origin, County_Code_Origin, State_Code_Dest, County_Code_Dest, County_Name, Exmpt_Num)
}))
# apply first year, since we're looking at outflows
year = c(2008, 2009, 2010)
master_outflow_csv$Year= rep(year, sapply(dataframes_outflow, nrow))
```

```{r}
# these require their own reading, since they're .dat files
file_paths_dat = c(
"../data_raw/countyout0405us1.dat",
"../data_raw/countyout0506.dat",
"../data_raw/countyout0607.dat",
"../data_raw/co0708us.dat")

# we need to manually specifiy the width of the columns, as the number of white spaces in each row varies a lot
col_widths = c(3, 4, 3, 4, 3, 35, 10, 11, 13, 5)

# applying first year, since we're looking at outflows
years = 2004:2007

# read.fwf command does what we need it to do, eventually
dataframes_dat = lapply(seq_along(file_paths_dat), function(i) {
  
  data = read.fwf(file_paths_dat[i], widths = col_widths, header = FALSE)
  
  data$Year = rep(years[i], nrow(data))
  
  data
})

master_outflow_dat = do.call(rbind, dataframes_dat)

# assign column names, so they're not all V1, V2, etc
colnames(master_outflow_dat) = c("State_Code_Origin", "County_Code_Origin", "State_Code_Dest",	"County_Code_Dest", "State_Abbrv",	"County_Name",	"Return_Num",	"Exmpt_Num",	"Aggr_AGI", "Misc Number", "Year"
)

# remove the miscellaneous column that does not appear in other datasets
master_outflow_dat = select(master_outflow_dat, select = -"Misc Number")
# combine the .dat files and the 08-10 csv files
outflow_0411 = bind_rows(master_outflow_dat, master_outflow_csv)
# get rid of unused columns, for ease of merging later
outflow_0411 = select(outflow_0411, -c("State_Abbrv", "Return_Num", "Aggr_AGI"))
```



```{r}
# read in all outflow files from 11-20
file_paths = c("../data_raw/countyoutflow1112.csv",
"../data_raw/countyoutflow1213.csv",
"../data_raw/countyoutflow1314.csv",
"../data_raw/countyoutflow1415.csv",
"../data_raw/countyoutflow1516.csv",
"../data_raw/countyoutflow1617.csv",
"../data_raw/countyoutflow1718.csv",
"../data_raw/countyoutflow1819.csv",
"../data_raw/countyoutflow1920.csv",
"../data_raw/countyoutflow2021.csv")
dataframes_outflow <- lapply(file_paths, read.csv)

# we select y1 here to pull out origin states
master_outflow <- do.call(rbind, lapply(dataframes_outflow, function(df) {
  select(df, y1_statefips, y1_countyfips, y2_statefips, y2_countyfips, y2_countyname, n2)
}))
# apply first year for outflows
year = c(2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)
master_outflow$Year= rep(year, sapply(dataframes_outflow, nrow))

```

```{r}
# rename the columns of our dataframe from 04-11 to be able to bind it to master_outflow
outflow_0411_renamed = outflow_0411 %>%
  rename(
    y2_statefips = State_Code_Dest,
y2_countyfips = County_Code_Dest,
y1_statefips = State_Code_Origin,
y1_countyfips = County_Code_Origin,
y2_countyname = County_Name,
n2 = Exmpt_Num
  )

# combine the 
master_outflow_0420 = bind_rows(outflow_0411_renamed, master_outflow)

# use the str_pad function from stringr to add our leading zeroes back in
master_outflow_0420$y1_statefips = str_pad(master_outflow_0420$y1_statefips, width = 2, side = "left", pad = "0")
master_outflow_0420$y1_countyfips = str_pad(master_outflow_0420$y1_countyfips, width = 3, side = "left", pad = "0")
master_outflow_0420$y2_statefips = str_pad(master_outflow_0420$y2_statefips, width = 2, side = "left", pad = "0")
master_outflow_0420$y2_countyfips = str_pad(master_outflow_0420$y2_countyfips, width = 3, side = "left", pad = "0")
```


```{r}
outflow_year = master_outflow_0420 %>% 
  filter(
    case_when(
    # no need for string detect here, as there is a row with the entire migration us and foreign, not specific to any county
    #between(Year, 2011, 2017) ~ y2_countyname == 'Total Migration-US and Foreign',
    
    # using string detect for partial strings, as each entry is appended with the name of the specific county that total is from
    between(Year, 2004, 2020) ~ str_detect(y2_countyname, 'County Total Migration-US and Foreign'))) %>% 
  group_by(Year) %>% 
  # group by year and sum to consolidate rows from years 2018-2020
  summarise(total_n2 = sum(n2))
```

```{r}
outflow_county_year =  master_outflow_0420 %>%
  # filter out y1_countyfips = 000 because these are state-level tallies of outflows
  filter(y1_countyfips != "000",
         # statefips 96, countyfips 000 for y2 is the sum columns for county (and state) rows
         y2_statefips == "96",
         y2_countyfips == "000") %>% 
  select(y1_statefips, y1_countyfips, n2, Year)
```

```{r}
# see above comments, code does the same work, years are += 1 to account for inflows being the latter year in the data
file_paths_csv = c(
"../data_raw/countyinflow0809.csv",
"../data_raw/countyinflow0910.csv",
"../data_raw/countyinflow1011.csv")

dataframes_inflow <- lapply(file_paths_csv, read.csv)
master_inflow_csv <- do.call(rbind, lapply(dataframes_inflow, function(df) {
  select(df, State_Code_Dest, County_Code_Dest, State_Code_Origin, County_Code_Origin, County_Name, Exmpt_Num)
}))
years <- c(2009, 2010, 2011)
master_inflow_csv$Year= rep(years, sapply(dataframes_inflow, nrow))
```

```{r}
file_paths_dat = c(
"../data_raw/countyin0405us1.dat",
"../data_raw/countyin0506.dat",
"../data_raw/countyin0607.dat",
"../data_raw/ci0708us.dat")

col_widths = c(3, 4, 3, 4, 3, 35, 10, 11, 13, 5)

years = 2005:2008

dataframes_dat = lapply(seq_along(file_paths_dat), function(i) {
  
  data = read.fwf(file_paths_dat[i], widths = col_widths, header = FALSE)
  
  data$Year = rep(years[i], nrow(data))
  
  data
})

master_inflow_dat = do.call(rbind, dataframes_dat)

colnames(master_inflow_dat) = c("State_Code_Dest", "County_Code_Dest", "State_Code_Origin",	"County_Code_Origin", "State_Abbrv",	"County_Name",	"Return_Num",	"Exmpt_Num",	"Aggr_AGI", "Misc Number", "Year"
)

master_inflow_dat = select(master_inflow_dat, select = -"Misc Number")
inflow_0411 = bind_rows(master_inflow_dat, master_inflow_csv)
inflow_0411 = select(inflow_0411, -c("State_Abbrv", "Return_Num", "Aggr_AGI"))
```

```{r}
# read in all inflow files
file_paths = c(
"../data_raw/countyinflow1112.csv",
"../data_raw/countyinflow1213.csv",
"../data_raw/countyinflow1314.csv",
"../data_raw/countyinflow1415.csv",
"../data_raw/countyinflow1516.csv",
"../data_raw/countyinflow1617.csv",
"../data_raw/countyinflow1718.csv",
"../data_raw/countyinflow1819.csv",
"../data_raw/countyinflow1920.csv",
"../data_raw/countyinflow2021.csv")
dataframes_inflow <- lapply(file_paths, read.csv)

# we select y1 here to pull out origin states
master_inflow <- do.call(rbind, lapply(dataframes_inflow, function(df) {
  select(df, y2_statefips, y2_countyfips, y1_statefips, y1_countyfips, y1_countyname, n2)
}))
year = c(2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021)
master_inflow$Year= rep(year, sapply(dataframes_inflow, nrow))
# use the str_pad function from stringr to add our leading zeroes back in
```

```{r}
master_inflow_renamed <- inflow_0411 %>%
  rename(
    y2_statefips = State_Code_Dest,
y2_countyfips = County_Code_Dest,
y1_statefips = State_Code_Origin,
y1_countyfips = County_Code_Origin,
y2_countyname = County_Name,
n2 = Exmpt_Num
  )

master_inflow_0521 = bind_rows(master_inflow_renamed, master_inflow)

master_inflow_0521$y1_statefips = str_pad(master_inflow_0521$y1_statefips, width = 2, side = "left", pad = "0")
master_inflow_0521$y1_countyfips = str_pad(master_inflow_0521$y1_countyfips, width = 3, side = "left", pad = "0")
master_inflow_0521$y2_statefips = str_pad(master_inflow_0521$y2_statefips, width = 2, side = "left", pad = "0")
master_inflow_0521$y2_countyfips = str_pad(master_inflow_0521$y2_countyfips, width = 3, side = "left", pad = "0")
```

```{r}
inflow_year = master_inflow_0521 %>% 
  filter(
    case_when(
    # no need for string detect here, as there is a row with the entire migration us and foreign, not specific to any county
    #between(Year, 2011, 2017) ~ y2_countyname == 'Total Migration-US and Foreign',
    
    # using string detect for partial strings, as each entry is appended with the name of the specific county that total is from
    between(Year, 2005, 2021) ~ str_detect(y2_countyname, 'County Total Migration-US and Foreign'))) %>% 
  group_by(Year) %>% 
  # group by year and sum to consolidate rows from years 2018-2020
  summarise(total_n2 = sum(n2))
```

```{r}
inflow_county_year =  master_inflow_0521 %>%
  filter(y2_countyfips != "000",      # Filter where y1_countyfips is not equal to zero
         y1_statefips == "96",     # Filter where y2_statefips is equal to 96
         y1_countyfips == "000") %>% 
  select(y2_statefips, y2_countyfips, n2, Year)
```


```{r}
means = outflow_county_year %>% 
  group_by(Year) %>% 
  summarise(mean_outflow = mean(n2))
print(means)

sds = outflow_county_year %>% 
  group_by(Year) %>% 
  summarise(sd_outflow = sd(n2))

print(sds)
```

```{r}
means = inflow_county_year %>% 
  group_by(Year) %>% 
  summarise(mean_inflow = mean(n2))
print(means)

sds = inflow_county_year %>% 
  group_by(Year) %>% 
  summarise(sd_outflow = sd(n2))

print(sds)
```

```{r}
# read in our county-level population file and set proper string padding
population = readRDS("../data_raw/pop_data.RDS")
population$FIPS = str_pad(population$FIPS, width = 5, side = "left", pad = "0")
```

```{r}
# split out the FIPS code into respective state and county FIPS
population = population %>% 
  mutate(
    statefips = substr(FIPS, 1, 2),
    countyfips = substr(FIPS, 3, nchar(FIPS))
  )
```

```{r}
outflow_county_year$y1_statefips <- as.character(outflow_county_year$y1_statefips)
outflow_county_year$y1_countyfips <- as.character(outflow_county_year$y1_countyfips)
# join our general outflow_county_year file with the population numbers
outflow_join = outflow_county_year %>% 
  inner_join(population, by = c("Year" = "year", "y1_statefips" = "statefips", "y1_countyfips" = "countyfips")) %>% 
  select(Year, y1_statefips, y1_countyfips, n2, pop_estimate)
```

```{r}
# calculate outflow per capita
outflow_join = outflow_join %>% 
  mutate(outflow_per_Capita = n2/ pop_estimate)
```

```{r}
# order the data properly for our year over year calculations
outflow_join <- outflow_join %>%
  arrange(y1_statefips, y1_countyfips, Year)

# Calculate the year-over-year percentage change
outflow_join <- outflow_join %>%
  group_by(y1_statefips, y1_countyfips) %>%
  mutate(percentage_change = (outflow_per_Capita - lag(outflow_per_Capita)) / lag(outflow_per_Capita) * 100)

```


```{r}
inflow_county_year$y2_statefips <- as.character(inflow_county_year$y2_statefips)
inflow_county_year$y2_countyfips <- as.character(inflow_county_year$y2_countyfips)

# join in population data
inflow_join = inflow_county_year %>% 
  inner_join(population, by = c("Year" = "year", "y2_statefips" = "statefips", "y2_countyfips" = "countyfips")) %>% 
  select(Year, y2_statefips, y2_countyfips, n2, pop_estimate)

# compute per capita data
inflow_join = inflow_join %>% 
  mutate(inflow_per_Capita = n2/ pop_estimate)

inflow_join <- inflow_join %>%
  arrange(y2_statefips, y2_countyfips, Year)

# Calculate the year-over-year percentage change
inflow_join <- inflow_join %>%
  group_by(y2_statefips, y2_countyfips) %>%
  mutate(percentage_change = (inflow_per_Capita - lag(inflow_per_Capita)) / lag(inflow_per_Capita) * 100)
```


```{r}
# this chunk will create our new error detection column by applying the ifelse statement
outflow_join <- outflow_join %>%
  group_by(y1_statefips, y1_countyfips) %>%
  mutate(
    data_issue_outflow = ifelse(
      n2 == -1 | percentage_change > 500 | percentage_change < -1000,
      1,
      0
    )
  )

inflow_join <- inflow_join %>%
  group_by(y2_statefips, y2_countyfips) %>%
  mutate(
    data_issue_inflow = ifelse(
      n2 == -1 | percentage_change > 500 | percentage_change < -1000,
      1,
      0
    )
  )

# sets NA values in data issue columns to equal 0 -- these were being caused by NA values in the percentage change columns for the first year of any county
outflow_join = outflow_join %>% 
  mutate(data_issue_outflow = replace(data_issue_outflow, is.na(data_issue_outflow), 0))

inflow_join = inflow_join %>% 
  mutate(data_issue_inflow = replace(data_issue_inflow, is.na(data_issue_inflow), 0))
```
